inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 130

AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seed.rb'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'node_modules/**/*'
    - 'bin/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
    - 'app/helpers/application_helper.rb'
    - 'spec/spec_helper.rb'
