default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: taku
  password: bbb19893245
  host: taku-mysql99.cccq6yiaqbbq.ap-northeast-1.rds.amazonaws.com

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  host: taku-mysql99.cccq6yiaqbbq.ap-northeast-1.rds.amazonaws.com
  database: DB_t
  username: taku
  password: bbb19893245
